### ISSUE TITLE
How can I build perl modules?

### ISSUE THREAD

**Issue by GitSoftwareNow** [Debian/debhelper#6]

**Comment by nthykier** [comment]
Hi,

I would recommend that you look at the guides from the Debian Perl packaging team as they have the most up to date documentation on that, which also includes the documentation for how to use debhelper for this purpose.

You can find more information on:

 * https://wiki.debian.org/Teams/DebianPerlGroup - under Useful Links.
 * https://packages.debian.org/sid/dh-make-perl - Tool for assisting with generating the *initial* package for a new perl-based Debian package.

If you are aiming for uploading the package to Debian, then I would recommend that you contact the Debian perl packaging team, who are experts in the field and also very open to new contributors.
