### ISSUE TITLE
weird issue w/ docdir

### ISSUE THREAD

**Issue by okias** [Debian/debhelper#7]
Repo: https://salsa.debian.org/okias-guest/libopusenc
Log:
```
make[1]: Leaving directory '/home/projects/debian/libopusenc'
   dh_install
	install -d debian/libopusenc0//usr/lib/x86_64-linux-gnu
	cp --reflink=auto -a debian/tmp/usr/lib/x86_64-linux-gnu/libopusenc.so debian/tmp/usr/lib/x86_64-linux-gnu/libopusenc.so.0 debian/tmp/usr/lib/x86_64-linux-gnu/libopusenc.so.0.4.2 debian/libopusenc0//usr/lib/x86_64-linux-gnu/
	install -d debian/libopusenc0//usr/share/doc/libopusenc
	cp --reflink=auto -a debian/tmp/usr/share/doc/libopusenc/AUTHORS debian/tmp/usr/share/doc/libopusenc/README.md debian/libopusenc0//usr/share/doc/libopusenc/
	install -d debian/.debhelper/generated/libopusenc0
	install -d debian/libopusenc-dev//usr/include/opus
	cp --reflink=auto -a debian/tmp/usr/include/opus/opusenc.h debian/libopusenc-dev//usr/include/opus/
	install -d debian/libopusenc-dev//usr/lib/x86_64-linux-gnu
	cp --reflink=auto -a debian/tmp/usr/lib/x86_64-linux-gnu/libopusenc.a debian/libopusenc-dev//usr/lib/x86_64-linux-gnu/
	install -d debian/libopusenc-dev//usr/lib/x86_64-linux-gnu/pkgconfig
	cp --reflink=auto -a debian/tmp/usr/lib/x86_64-linux-gnu/pkgconfig/libopusenc.pc debian/libopusenc-dev//usr/lib/x86_64-linux-gnu/pkgconfig/
	install -d debian/.debhelper/generated/libopusenc-dev
	install -d debian/.debhelper/generated/libopusenc-doc
   dh_installdocs
	install -d debian/libopusenc0/usr/share/doc/libopusenc0
	install -p -m0644 debian/copyright debian/libopusenc0/usr/share/doc/libopusenc0/copyright
	install -d debian/libopusenc-dev/usr/share/doc/libopusenc-dev
	install -p -m0644 debian/copyright debian/libopusenc-dev/usr/share/doc/libopusenc-dev/copyright
	install -d debian/libopusenc-doc/usr/share/doc/libopusenc-doc
	install -d debian/libopusenc-doc/usr/share/doc/libopusenc-dev
	cd 'debian/tmp/usr/share/doc/libopusenc/html/..' && find 'html' \( -type f -or -type l \) -and ! -empty -print0 | LC_ALL=C sort -z | xargs -0 -I {} cp --reflink=auto --parents -dp {} /home/projects/debian/libopusenc/debian/libopusenc-doc/usr/share/doc/libopusenc-dev
	chmod -R u\+rw,go=rX debian/libopusenc-doc/usr/share/doc
	install -p -m0644 debian/copyright debian/libopusenc-doc/usr/share/doc/libopusenc-doc/copyright
	install -d debian/libopusenc-doc/usr/share/doc-base/
	install -p -m0644 debian/libopusenc-doc.doc-base debian/libopusenc-doc/usr/share/doc-base/libopusenc

```

I cannot figure out, how gets this path assembled: 
`/home/projects/debian/libopusenc/debian/libopusenc-doc /usr/share/doc/libopusenc-dev`
/home/projects/debian/libopusenc/debian/libopusenc **-doc** (correct) /usr/share/doc/libopusenc **-dev** (wrong)

Except existing entry in control file for libopusenc-dev, I cannot see where it could pick it.

Any ideas? Thank you

**Comment by nthykier** [comment]
David Heidelberg:
> Repo: https://salsa.debian.org/okias-guest/libopusenc
> Log:
> [...]
> 
> I cannot figure out, how gets this path assembled: 
> `/home/projects/debian/libopusenc/debian/libopusenc-doc /usr/share/doc/libopusenc-dev`
> /home/projects/debian/libopusenc/debian/libopusenc **-doc** (correct) /usr/share/doc/libopusenc **-dev** (wrong)
> 
> Except existing entry in control file for libopusenc-dev, I cannot see where it could pick it.
> 
> Any ideas? Thank you
> 

Hi,

A quick guess makes me think that this is intentional and related to
Debian Policy §12.3.  Namely, Debian has decided that "-doc" packages
should use the "main" package's package name for the docs.

The main package is vaguely defined and debhelper has some heuristics.
For a library it /can/ be a -dev package on the assumption that the docs
are developer docs.

If the guess is wrong, then you can use dh_installdocs
--doc-main-package <...> to overwrite the guessing mechanism.

**Comment by okias** [comment]
Thank you @nthykier it solved my issue (I generally put these few docs into -dev and aligned -dev name), not sure if I should fill bug for it, likely not I guess.
